server:
  port: 8085

spring:
  boot:
    admin:
      client:
        url: http://localhost:8090
  zipkin:
    base-url: http://localhost:8088
  application:
    name: spring-cloud-fegin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
# 开启熔断策略
feign:
  hystrix:
    enabled: true